spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: loggers, shutdown

server:
  shutdown: graceful
  port: 9090